### ISSUE TITLE
Add To Dictionary Support

### ISSUE THREAD

**Issue by archcorsair** [Dennislampert/spell-check-case#1]
Would be nice to be able to add a word to dictionary, some variable names cannot be changed, like: `lodash`, `polyfill`, `eslint`, etc.

**Comment by Dennislampert** [comment]
Just released a new version. 1.0.0
It can add words through the command palette and is better to use.
Select the word you like to add and open the command palette with your key-shortcut and type "add word" press enter and it't should not hint that word anymore 👍 
Hope you like it.

**Comment by archcorsair** [comment]
Thank you! 🥇
